### PR TITLE
Replace GPG key short id for full fingerprint

### PR DESCRIPTION
**Pull request by chipironcin**
Prevent dead beef attack

### CODE REVIEW

**Comment by chipironcin** [comment]
Dead Beef Attack definition:
>An attack on a public-key cryptosystem consisting of publishing a key having the same ID as another key (thus making it possible to spoof a user's identity if recipients aren't careful about verifying keys). In PGP and GPG the key ID is the last eight hex digits of (for RSA keys) the product of two primes.

The attack was demonstrated on 1996
Source:
http://www.catb.org/jargon/html/D/dead-beef-attack.html

A pretty recent example of the attack by submitting keys with short ID identical to an existing trusted key:
https://lkml.org/lkml/2016/8/15/445

**Comment by krallin** [comment]
Thanks; this definitely deserves fixing! There are a few tweaks I'd love to make before merging this:

- Can you squash the two commits? That's mostly to preserve a clean history for e.g. `git blame`
- Can you quote the variables ` $PGP_KEYSERVER` and `$PGP_KEY_FINGERPRINT` when using them (i.e. `"$PGP_KEY_FINGERPRINT"`). I don't foresee those being a problem, but that's arguably good shell script hygiene 😄 
- You might also want to rename the variables from `PGP_...` to `GPG_...` for consistency with the existing ones, and rename `PGP_KEY_FINGERPRINT` to `PGP_KEY_ID` for accuracy. This is mostly cosmetic and doesn't make a functional difference. 

Please do feel free to make those changes yourself, but you don't *have* to: I can always amend your commits myself and merge them next week otherwise (I'm currently on vacation).

Thanks again!

**Comment by chipironcin** [comment]
I am happy of improving those commits and follow guidelines you may want to preserve for your repo.
1. Will try to squash them
2. Yes, good practice to quote them
3. In fact, the fingerprint and the keyserver refer to PGP(OpenPGP standard) but the other two variables refer to GPG (GnuPGP) paths. I also have that question when writing this as I wanted to keep the same prefix but they are different things. Not sure how to exactly proceed. Despite that, I would accept renaming them to GPG prefix if you prefer.

About `PGP_KEY_FINGERPRINT` to `PGP_KEY_ID`, I am using, in fact, the `FINGERPRINT` of the key. It can be also considered an `ID` so you can check a key by its `FINGERPRINT/FULL_ID`, `LONG_ID` or `SHORT_ID` like we had there. I think using `FINGERPRINT` here is the most accurate way of calling it 😛 

Waiting for your comments about this, I am open to modifying this up to your preferences anyways.

Enjoy vacations dude!

**Comment by krallin** [comment]
Hey @chipironcin,

> 1. Will try to squash them

Thanks!

> 2. Yes, good practice to quote them

Great.

> 3. In fact, the fingerprint and the keyserver refer to PGP(OpenPGP standard) but the other two variables refer to GPG (GnuPGP) paths. I also have that question when writing this as I wanted to keep the same prefix but they are different things. Not sure how to exactly proceed. Despite that, I would accept renaming them to GPG prefix if you prefer.

Fair enough; no need to change. 

--

Let me know once you've been able to make the tweaks in 1 / 2 and I'll merge. Thanks again!

**Comment by chipironcin** [comment]
@krallin Can you confirm you can click on the merge button from Github UI while selecting the option "Squash"?
https://github.com/blog/2141-squash-your-commits

**Comment by krallin** [comment]
Yes; thanks! Guess asking you to rebase might have been a little old-school 😄

**Comment by chipironcin** [comment]
Oh, I should have done that to save you from merge issues :P
Thanks for keeping on top of this. Hope you enjoyed your vacations.
Regards

**Pull request merged**
