### PR TITLE
Tini static from tianon

### PR DESCRIPTION
**Pull request by krallin**
See: #3

### CODE REVIEW

**Comment by tianon** [comment]
:metal:

**Comment by krallin** [comment]
And it's live! : )

https://github.com/krallin/tini/releases/download/v0.5.0/tini_0.5.0.deb

Cheers,

**Comment by krallin** [comment]
Correct link = much better

https://github.com/krallin/tini/releases/download/v0.5.0/tini-static

**Comment by tianon** [comment]
:heart:!

**Pull request merged**
