### PR TITLE
Moved alpine package to community repository

### LINKED ISSUE #31: Move alpine package to community repos
@krallin this is just a reminder for me so i don't forget on the next release

### PR DESCRIPTION
**Pull request by danilobuerger**
Closes #31

### CODE REVIEW

**Comment by krallin** [comment]
Hey @danilobuerger, thanks a ton!

Nevermind the status check. I'll disable it and merge this in (I didn't expect this would fail when the keys were missing, but whatever). 

When I try to install, I still get a package not found error.:

```
thomas@mocha4 ~ % docker run -it alpine apk add --update tini                              
fetch http://dl-4.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://dl-4.alpinelinux.org/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  tini (missing):
    required by: world[tini]
```

I'm assuming this probably just needs a little time to make it to the public repos. I'll try again in a bit and merge as soon as this seems to go through reliably.

Thanks again!

Cheers

**Comment by danilobuerger** [comment]
3.3 is frozen, so it appears in edge only for now and then 3.4. If the docker image of alpine uses the 3.3 packages by default, we should probably leave the repository flag in the command. I will amend the commit.

**Comment by tianon** [comment]
It works in `alpine:edge` for sure! :smile:
```console
$ docker run -it --rm alpine:edge apk add --no-cache tini
fetch http://dl-4.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-4.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
(1/1) Installing tini (0.9.0-r0)
Executing busybox-1.24.1-r7.trigger
OK: 5 MiB in 12 packages
```

**Comment by danilobuerger** [comment]
@krallin ping

**Comment by krallin** [comment]
Thanks @danilobuerger !

**Pull request merged**
