### PR TITLE
Use -static for full static compilation

### PR DESCRIPTION
**Pull request by tianon**
This allows the use of `tini` within even more minimal environments (such as images that are `FROM scratch` with a single application binary `COPY`'d in).

This is just a proposal, so I'm definitely willing to debate and/or update and/or close, but I think this is worth discussing. :smile:

### CODE REVIEW

**Comment by krallin** [comment]
Hey @tianon; thanks for the PR!

I originally had static compilation in Tini, but took it out because it was breaking clang builds and I didn't feel it was useful enough to bother finding out what the problem was (https://github.com/krallin/tini/commit/699c3aadf25944975a390fa1bd333eb1ef4b5d89). You fixing it takes *that* out of the equation, so I'm all for having a static build. : )

Now, I'd rather have two build targets (a static one and a dynamic one), rather than static-only. Any reason not to? Let me know what you think.

**Comment by krallin** [comment]
Oh, and just to be clear: when I say "I'd rather have two", I'm not asking you to do it. I can use your code and add some of the old one I linked earlier to do so.

(though obviously, if you *want* to do it, I'll merge it! :) )

Cheers,

**Comment by tianon** [comment]
That sounds fantastic!  I just want to make sure I can use your published binaries instead of compiling my own. :heart:

I'll openly admit that my CMake-fu is not nearly strong enough for me to easily adapt this to have two targets, so feel free to steal all my work to make this happen how you want it done. :+1:

**Comment by tianon** [comment]
Oh, looking at that commit, I think I could hammer this out.  Give me a little time and I'll punt again if I can't get it done. :+1:

**Comment by krallin** [comment]
I see you updated it, thanks!

I'm going to check whether the images build properly and merge this in if so (I might not have time to do it tonight but if so I'll get to it tomorrow).

Thanks again!

**Comment by tianon** [comment]
I _think_ I got everything, but obviously feel free to comment if anything looks out of place in what I've done. :smile:

(a few places have changed a bit since that older commit)

**Comment by tianon** [comment]
Thanks for saving me from having to create this utility myself. :+1:

**Comment by tianon** [comment]
Awesome, sounds good!  I'm in no rush (my current use cases are fine with non-static), so take the time you need. :heart:

**Comment by krallin** [comment]
I had to make a few changes (basically updating the template files instead of the resulting files, and fixing the valgrind test which doesn't like static binaries).

I'm going to push those as a separate PR: #4. (I don't think I can make changes to *this* PR, but I made sure to retain the author).

Thanks again!

**Pull request closed without merging**
