### PR TITLE
Pass tty to child process group and release 0.8.1

### LINKED ISSUE #19: Interactive Terminal / TTY Hangup
When using tini with a TTY, interactive shell commands like `python` and `irb` hang the terminal. Either of the following Dockerfiles will reproduce the issue (`python` can be replaced with `ruby`, etc.):

```dockerfile
FROM krallin/ubuntu-tini:trusty
RUN apt-get update && apt-get install -y --no-install-recommends python
```

```dockerfile
FROM debian:8.2

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates curl libc6 python && \
    curl -sSL "https://github.com/krallin/tini/releases/download/v0.8.0/tini" -o /usr/bin/tini && \
    chmod +x /usr/bin/tini && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/bin/tini", "--"]
```

```bash
$ docker build -t tini-tty .
$ docker run --rm -it tini-tty python
```

Commenting out the `ENTRYPOINT` and rebuilding the image results in a working TTY session. Non-interactive commands, such as `$ docker run --rm -it tini-tty python --version` work just fine.

Am I missing something simple here like an option? Thanks!

### PR DESCRIPTION
**Pull request by krallin**
Fixes #19

### CODE REVIEW

**Comment by dpw** [comment]
Make sense. #15 meant that only the tini process was in the foreground process group.

I started testing the ctrl-C behaviour of this branch, and in some cases I was surprised by what happened.  I realized that I didn't fully understand the effect of the docker run `-t` and `-i` options (they are not very clearly documented), so I started testing systematically.  I went on to test the behaviour of a plain ubuntu image, ubuntu with tini 0.8.0 (without `-g`), this branch, and this branch with the `-g` option on the entrypoint.  And here are the results:

Command | ubuntu | tini 0.8.0 | fix-19-pass-tty | fix-19-pass-tty + -g
---------------|-----------|--------------|----------------|-------------------------------------------
docker run --rm image sleep 10 | wait | exit | exit | exit
docker run --rm image sh -c "sleep 10" | wait | wait | wait | exit
docker run --rm -i image sleep 10 | wait | exit | exit | exit
docker run --rm -i image sh -c "sleep 10" | wait | wait | wait | exit
docker run --rm -t image sleep 10 | detach | detach | detach | detach
docker run --rm -t image sh -c "sleep 10" | detach | detach | detach | detach
docker run --rm -t -i image sleep 10 | wait | exit | exit | exit
docker run --rm -t -i image sh -c "sleep 10" | exit | wait | exit | exit

"wat" means the command waited for the full 10 seconds.  "exit" means the command exited promptly after ctrl-C was typed.  "detach" means the command exited, but the container continued to run for the full 10 seconds.

Conclusions:

* `-i` without `-t` seems to have no effect in these tests (but note that `-i` with `-d` does have an effect compared to `-d` alone).

* `-t` without `-i` employs a ptty, but does not relay stdin to it, and ctrl-C simply kills the docker client.

* The `docker run --rm -t -i image sh -c "sleep 10"` line is interesting.  It's the only case I found where this branch makes a difference, and I guess it is the point of this pull request.

* The `-g` option still seems to have a clear purpose with this branch.

**Comment by dpw** [comment]
For the SIGTTOU/SIGTTIN change, I wonder if it is possible to achieve the same effect with less code by

* Blocking SIGTTOU and SIGTTIN in the parent right at the start
* Unblocking them in the child after the fork
* In the parent after the fork, set those signals to SIG_IGN and unblock them.

This would avoid the need to save and restore the handlers. But I must admit I don't fully understand the TOSTOP mechanism, so I'm not sure it's equivalent.

**Comment by krallin** [comment]
Hey @dpw , thanks a lot for the systematic testing. This is helpful. 

Just in case you're interested, here's an extra bit of info regarding `-i`. Essentially, `-i` asks the client not to detach from the container you're running. However, if you do add `-t` but not `-i`, you can still use `docker attach`, to e.g. issue CTRL+C.

---

Now, regarding your other point: 

> For the SIGTTOU/SIGTTIN change, I wonder if it is possible to achieve the same effect with less code by
>
> + Blocking SIGTTOU and SIGTTIN in the parent right at the start
> + Unblocking them in the child after the fork
> + In the parent after the fork, set those signals to SIG_IGN and unblock them.

I'm saving and restoring the handlers mainly to ensure that Tini is as transparent as possible. 

I don't expect that to be very useful in real life, but I figure that if a user goes out of their way to set those signals before launching Tini, it's best for Tini to respect that. I was already doing it with the signals we block, so I figured it was just as easy to do the same thing for `SIGTTOU` and `SIGTTIN`.

In that regard, I should probably also ensure that Tini only passes the tty if it currently owns it.

Now, to your suggestion of unblocking them right after the fork.

That's what I was originally doing; unfortunately, it didn't work because when the child runs `tcsetpgrp`, it gets sent a `SIGTTOU` (because it doesn't own the terminal at this point, since we have to change `pgrp` before running `tcsetpgrp`). 

I originally worked around the issue by running `tcsetpgrp` in the parent, but this created a race condition in case the program being spawned was also forking and running `tcsetpgrp` (e.g. if you're spawning a shell, or Tini itself — which I've seen one or two instances of in the wild). The [comments here](https://github.com/krallin/tini/pull/21/files#diff-ca891f8f15a3d8ee378ae5f80f0b46c3R94)  explain that in more detail.

So, in the end I settled for restoring after running `tcsetpgrp`.

---

The `TOSTOP` / `SIGTTOU` / `SIGTTIN` mechanism is a bit complex and not very well documented, but here are some references:

+ [`tty_check_change` source code](http://lxr.free-electrons.com/source/drivers/tty/tty_io.c?v=4.2#L388)
+ [Darwin Man Pages](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man4/termios.4.html) — search the page for `SIGTTOU` (this isn't Linux docs, but this behavior appears to be specified in POSIX).
+ Libc Shell Tutorial: [Initializing the shell](http://www.gnu.org/software/libc/manual/html_node/Initializing-the-Shell.html#Initializing-the-Shell), [Launching Jobs](http://www.gnu.org/software/libc/manual/html_node/Launching-Jobs.html#Launching-Jobs), [Foreground and Background](http://www.gnu.org/software/libc/manual/html_node/Foreground-and-Background.html#Foreground-and-Background)

Cheers,

**Comment by krallin** [comment]
(forget that bit about `-i` in my previous message, not sure I got that right)

**Pull request merged**
