### PR TITLE
credit nfnty for packaging tini for Arch Linux

### PR DESCRIPTION
**Pull request by cmeury**

### CODE REVIEW

**Comment by krallin** [comment]
Hey @cmeury,

Do you know if this is usable by other users on Arch and might eventually become an official package? (the other packages in this section have, but I'm happy to add a section with Arch instructions in there)

Thanks!

**Comment by cmeury** [comment]
The AUR is a common place for people to get their packages from; but you're right, it's not official. I wouldn't assume it makes it into the official repositories very soon, so feel free to close this PR.

**Comment by krallin** [comment]
Thanks @cmeury. I'm not super familiar with Arch. How would one go about using @nfnty's  repo to install Tini on their system?

With that information, I'd be happy to add at least a section linking to it. I'm assuming the reason you opened this PR originally was because you had a hard time finding this and hoped to help other users find it more easily :)

Thanks!

**Comment by tonylambiris** [comment]
@krallin The AUR stands for the Arch Linux User Repository.

Arch works differently than, say ubuntu. Instead of having a bunch of ppa/repos, any contributed packages are hosted on `aur.archlinux.org` using standard git commands to push any changes made locally for it to become visible in the AUR.

Getting back to `tini`, there's nothing really much to reference other than what has already been mentioned. It's already up and available in the AUR: https://aur.archlinux.org/packages/tini/

**Comment by krallin** [comment]
I'm not sure why this took me so long.... But, credit where credit is due is important and I merged this manually now..

**Pull request closed without merging**
