### PR TITLE
"White label" when MINIMAL is set

### PR DESCRIPTION
**Pull request by krallin**
Hey @crosbymichael,

Here's a proposed implementation for what I suggested in https://github.com/krallin/tini/pull/59 — let me know what you think. I also fixed a few issues with the current NO_ARGS implementation (namely: we were still showing the args in Usage).

Let me know what you think, with this patch, if you run an unknown command, you get:

```
root@1693b2f7195c:/# /dist/tini xx
exec xx failed: No such file or directory
```

I incorporate your status code changes, and added tests. I haven't been able to get `ENOEXEC` to show up (I tested with a binary from the wrong architecture, and with a shebang that points to nowhere), so I take back what my suggestion to include it 😄 

Finally, I updated the default log level to be fatal-only, since the warn level shows a few things that are probably irrelevant to end users. If someone wants to do more debugging, they can use `TINI_VERBOSITY`.

Cheers,

### CODE REVIEW

**Comment by krallin** [comment]
(Also added you to contributors, just let me know if you'd rather not of course)

**Comment by crosbymichael** [comment]
Thanks, reviewing

**Comment by crosbymichael** [comment]
LGTM

**Comment by krallin** [comment]
Awesome. Did you want me to rename the `NO_ARGS` option to something a bit clearer (e.g. `DOCKERINIT`)? You'd have to tweak it on your end as well if so.

**Comment by crosbymichael** [comment]
@krallin whatever you want to call it.  I think something generic is fine because we don't want to have a difference between the two versions.  Its more about stripping out a couple features ( cli args, verbose logs ) than building it for docker.  

I think something generic is cleaner.

**Comment by krallin** [comment]
Sounds good; I renamed the arg to `MINIMAL`. 

Cheers,

**Comment by crosbymichael** [comment]
LGTM

**Comment by krallin** [comment]
0.13 is live

**Pull request merged**
